/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AdoptionWithPetDtoStatus } from "./adoptionWithPetDtoStatus";
import type { PetDto } from "./petDto";

export interface AdoptionWithPetDto {
  /** 분양 ID */
  adoptionId: string;
  /** 펫 ID */
  petId: string;
  /** 분양 가격 */
  price?: number;
  /** 분양 날짜 */
  adoptionDate?: string;
  /** 메모 */
  memo?: string;
  /** 생성일 */
  createdAt: string;
  /** 수정일 */
  updatedAt: string;
  /** 펫 판매 상태 */
  status: AdoptionWithPetDtoStatus;
  /** 펫 정보 */
  pet: PetDto;
}
