/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { AdoptionDto } from "./adoptionDto";

/**
 * 분양 정보 (없을 수 있음)
 * @nullable
 */
export type AdoptionDetailResponseDtoData = AdoptionDto | null;
