/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface AdoptionRevenueDto {
  /** 총 수익 */
  totalRevenue: number;
  /** 평균 분양가 */
  averagePrice: number;
  /** 최저 분양가 */
  minPrice: number;
  /** 최고 분양가 */
  maxPrice: number;
}
