/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface AdoptionDayOfWeekItemDto {
  /** 분양 수 */
  count: number;
  /** 수익 */
  revenue: number;
  /** 평균 분양가 */
  averagePrice: number;
  /** 요일 (0=일, 1=월, ..., 6=토) */
  dayOfWeek: number;
}
