/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { StatisticsPeriodDto } from "./statisticsPeriodDto";
import type { AdoptionRevenueDto } from "./adoptionRevenueDto";
import type { AdoptionSexItemDto } from "./adoptionSexItemDto";
import type { AdoptionDistributionItemDto } from "./adoptionDistributionItemDto";
import type { AdoptionMonthlyItemDto } from "./adoptionMonthlyItemDto";
import type { AdoptionDayOfWeekItemDto } from "./adoptionDayOfWeekItemDto";
import type { CustomerAnalysisDto } from "./customerAnalysisDto";

export interface AdoptionStatisticsDto {
  /** 기간 정보 */
  period: StatisticsPeriodDto;
  /** 총 분양 수 */
  totalCount: number;
  /** 수익 통계 */
  revenue: AdoptionRevenueDto;
  /** 성별 통계 */
  sex: AdoptionSexItemDto[];
  /** 모프 분포 */
  morphs: AdoptionDistributionItemDto[];
  /** 형질 분포 */
  traits: AdoptionDistributionItemDto[];
  /** 분양 방식 분포 */
  methods: AdoptionDistributionItemDto[];
  /** 월별 통계 (연도만 선택된 경우) */
  monthlyStats?: AdoptionMonthlyItemDto[];
  /** 요일별 통계 */
  dayOfWeekStats?: AdoptionDayOfWeekItemDto[];
  /** 고객 분석 */
  customerAnalysis?: CustomerAnalysisDto;
}
