/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface AdoptionMonthlyItemDto {
  /** 월 (1-12) */
  month: number;
  /** 분양 수 */
  count: number;
  /** 수익 */
  revenue: number;
}
