/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface AdoptionSexStatisticsDto {
  /** 수컷 수 */
  male: number;
  /** 암컷 수 */
  female: number;
  /** 미확인 수 */
  unknown: number;
  /** 수컷 비율 (%) */
  maleRate: number;
  /** 암컷 비율 (%) */
  femaleRate: number;
  /** 수컷 총 수익 */
  maleRevenue: number;
  /** 암컷 총 수익 */
  femaleRevenue: number;
  /** 미확인 총 수익 */
  unknownRevenue: number;
  /** 수컷 평균 분양가 */
  maleAveragePrice: number;
  /** 암컷 평균 분양가 */
  femaleAveragePrice: number;
}
