/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface AdoptionSexItemDto {
  /** 성별 키 (male, female, unknown) */
  key: string;
  /** 개수 */
  count: number;
  /** 비율 (%) */
  rate: number;
  /** 총 수익 */
  revenue: number;
  /** 평균 분양가 */
  averagePrice: number;
}
