/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type BrPetControllerFindAllGrowth =
  (typeof BrPetControllerFindAllGrowth)[keyof typeof BrPetControllerFindAllGrowth];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BrPetControllerFindAllGrowth = {
  BABY: "BABY",
  ADULT: "ADULT",
  JUNIOR: "JUNIOR",
  SENIOR: "SENIOR",
} as const;
