/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type BrPetControllerFindAllSex =
  (typeof BrPetControllerFindAllSex)[keyof typeof BrPetControllerFindAllSex];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BrPetControllerFindAllSex = {
  M: "M",
  F: "F",
  N: "N",
} as const;
