/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserDto } from "./userDto";
import type { PageMetaDto } from "./pageMetaDto";

export type BrUserControllerGetUsers200 = {
  data: UserDto[];
  meta: PageMetaDto;
};
