/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface CreatePairDto {
  /** 주인 아이디 */
  ownerId: string;
  /** 아빠 펫 아이디 */
  fatherId?: string;
  /** 엄마 펫 아이디 */
  motherId?: string;
}
