/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 펫 성장단계
 */
export type CreatePetDtoGrowth = (typeof CreatePetDtoGrowth)[keyof typeof CreatePetDtoGrowth];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePetDtoGrowth = {
  BABY: "BABY",
  ADULT: "ADULT",
  JUNIOR: "JUNIOR",
  SENIOR: "SENIOR",
} as const;
