/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface CustomerDetailDto {
  /** 고객 ID */
  userId: string;
  /** 고객 이름 */
  name: string;
  /** 구매 횟수 */
  purchaseCount: number;
  /** 총 구매 금액 */
  totalSpending: number;
}
