/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { CustomerDetailDto } from "./customerDetailDto";

export interface CustomerAnalysisDto {
  /** 총 고객 수 (구매자) */
  totalCustomers: number;
  /** 재구매 고객 수 (2회 이상 구매) */
  repeatCustomers: number;
  /** 재구매율 (%) */
  repeatRate: number;
  /** 고객당 평균 구매 횟수 */
  averagePurchaseCount: number;
  /** 고객당 평균 구매 금액 */
  averageCustomerSpending: number;
  /** 상위 고객 목록 (구매금액 순) */
  topCustomers?: CustomerDetailDto[];
  /** 재구매 고객 목록 */
  repeatCustomerList?: CustomerDetailDto[];
}
