/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { DeletedPetDtoSpecies } from "./deletedPetDtoSpecies";

export interface DeletedPetDto {
  /** 삭제된 펫 이름 */
  name?: string;
  /** 펫 종 */
  species?: DeletedPetDtoSpecies;
  /** 펫 삭제 일시 */
  deletedAt?: string;
  /** 펫 삭제 사유 */
  deleteReason?: string;
  /** 분양 펫 아이디 */
  petId: string;
  /** 펫 출생일 */
  hatchingDate?: string;
}
