/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface DistributionItemDto {
  /** 항목명 */
  key: string;
  /** 개수 */
  count: number;
  /** 비율 (%) */
  percentage: number;
}
