/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface EggStatisticsDto {
  /** 전체 알 수 */
  total: number;
  /** 유정란 수 */
  fertilized: number;
  /** 무정란 수 */
  unfertilized: number;
  /** 부화 완료 수 */
  hatched: number;
  /** 중지란/사망 수 */
  dead: number;
  /** 미정 수 (상태 미확인) */
  pending: number;
  /** 유정란 비율 (%) */
  fertilizedRate: number;
  /** 부화 성공율 (%) */
  hatchingRate: number;
}
