/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetParentDto } from "./petParentDto";
import type { PetHiddenStatusDto } from "./petHiddenStatusDto";

/**
 * 아빠 펫 정보 (비공개인 경우 hiddenStatus만 포함)
 */
export type GetSiblingsWithDetailsDataDtoFather = PetParentDto | PetHiddenStatusDto;
