/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { GetSiblingsWithDetailsDataDtoFatherId } from "./getSiblingsWithDetailsDataDtoFatherId";
import type { GetSiblingsWithDetailsDataDtoMotherId } from "./getSiblingsWithDetailsDataDtoMotherId";
import type { SiblingPetDetailDto } from "./siblingPetDetailDto";

export interface GetSiblingsWithDetailsDataDto {
  /** 아빠 펫 ID */
  fatherId?: GetSiblingsWithDetailsDataDtoFatherId;
  /** 엄마 펫 ID */
  motherId?: GetSiblingsWithDetailsDataDtoMotherId;
  /** 형제 펫 목록 */
  siblings: SiblingPetDetailDto[];
}
