/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { GetSiblingsWithDetailsDataDto } from "./getSiblingsWithDetailsDataDto";

export interface GetSiblingsWithDetailsResponseDto {
  /** 성공 여부 */
  success: boolean;
  /** 메시지 */
  message: string;
  /** 형제 펫 정보 */
  data: GetSiblingsWithDetailsDataDto;
}
