/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 아빠 펫 ID
 */
export type GetSiblingsWithDetailsDataDtoFatherId = { [key: string]: unknown };
