/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 숨김 여부
 */
export type HiddenParentDtoIsHidden =
  (typeof HiddenParentDtoIsHidden)[keyof typeof HiddenParentDtoIsHidden];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HiddenParentDtoIsHidden = {
  SECRET: "SECRET",
  PENDING: "PENDING",
  DELETED: "DELETED",
} as const;
