/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { LayingDtoEggType } from "./layingDtoEggType";

export interface LayingDto {
  /** Laying ID */
  id: number;
  /** 클러치 순서 */
  layingOrder: number;
  /** 알 상태 */
  eggType?: LayingDtoEggType;
  /** 알 ID */
  eggId: string;
  /** 해칭 온도 */
  temperature?: number;
}
