/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 알 상태
 */
export type LayingDtoEggType = (typeof LayingDtoEggType)[keyof typeof LayingDtoEggType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LayingDtoEggType = {
  FERTILIZED: "FR",
  UNFERTILIZED: "UN",
} as const;
