/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface LayingDto {
  /** Laying ID */
  id: number;
  /** Mating ID */
  matingId?: number;
  /** Laying Date */
  layingDate: string;
  /** 차수(클러치) */
  clutch?: number;
  /** 차수(클러치) 순서 */
  clutchOrder?: number;
}
