/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { LinkParentDtoRole } from "./linkParentDtoRole";

export interface LinkParentDto {
  /** 부모 펫 아이디 */
  parentId: string;
  /** 부모 역할 */
  role: LinkParentDtoRole;
  /** 연동 요청 메시지 */
  message?: string;
}
