/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetSummaryDto } from "./petSummaryDto";
import type { MatingByDateDto } from "./matingByDateDto";

export interface MatingByParentsDto {
  /** 아빠 펫 정보 */
  father?: PetSummaryDto;
  /** 엄마 펫 정보 */
  mother?: PetSummaryDto;
  /** 메이팅 정보 */
  matingsByDate: MatingByDateDto[];
}
