/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface MonthlyStatisticsItemDto {
  /** 월 (1-12) */
  month: number;
  /** 총 알 수 */
  total: number;
  /** 유정란 수 (부화 포함) */
  fertilized: number;
  /** 무정란 수 */
  unfertilized: number;
  /** 중지란/사망 수 */
  dead: number;
  /** 미정 수 (상태 미확인) */
  pending: number;
  /** 부화 완료 수 */
  hatched: number;
}
