/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { StatisticsPeriodDto } from "./statisticsPeriodDto";
import type { EggStatisticsDto } from "./eggStatisticsDto";
import type { DistributionItemDto } from "./distributionItemDto";
import type { SexStatisticsDto } from "./sexStatisticsDto";
import type { StatisticsMetaDto } from "./statisticsMetaDto";

export interface PairStatisticsDto {
  /** 페어 ID */
  pairId: number;
  /** 기간 정보 */
  period: StatisticsPeriodDto;
  /** 알 통계 */
  egg: EggStatisticsDto;
  /** 모프 분포 */
  morphs: DistributionItemDto[];
  /** 형질 분포 */
  traits: DistributionItemDto[];
  /** 성별 통계 */
  sex: SexStatisticsDto;
  /** 메타 정보 */
  meta: StatisticsMetaDto;
}
