/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 부모 연동 상태
 */
export type ParentLinkDetailJsonStatus =
  (typeof ParentLinkDetailJsonStatus)[keyof typeof ParentLinkDetailJsonStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParentLinkDetailJsonStatus = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  DELETED: "deleted",
  CANCELLED: "cancelled",
} as const;
