/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetControllerGetDeletedPetsOrder } from "./petControllerGetDeletedPetsOrder";
import type { PetControllerGetDeletedPetsSpecies } from "./petControllerGetDeletedPetsSpecies";
import type { PetControllerGetDeletedPetsSexItem } from "./petControllerGetDeletedPetsSexItem";
import type { PetControllerGetDeletedPetsStatus } from "./petControllerGetDeletedPetsStatus";
import type { PetControllerGetDeletedPetsGrowthItem } from "./petControllerGetDeletedPetsGrowthItem";
import type { PetControllerGetDeletedPetsFilterType } from "./petControllerGetDeletedPetsFilterType";

export type PetControllerGetDeletedPetsParams = {
  /**
   * 정렬 순서
   */
  order?: PetControllerGetDeletedPetsOrder;
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지당 항목 수
   */
  itemPerPage?: number;
  /**
   * 검색 키워드 (이름, 설명 등)
   */
  keyword?: string;
  /**
   * 펫 종
   */
  species?: PetControllerGetDeletedPetsSpecies;
  /**
   * 펫 성별
   */
  sex?: PetControllerGetDeletedPetsSexItem[];
  /**
   * 펫 소유자 아이디
   */
  ownerId?: string;
  /**
   * 펫 공개 여부
   */
  isPublic?: number;
  /**
   * 펫 최소 몸무게
   */
  minWeight?: number;
  /**
   * 펫 최대 몸무게
   */
  maxWeight?: number;
  /**
   * 펫 최소 생년월일
   */
  startYmd?: string;
  /**
   * 펫 최대 생년월일
   */
  endYmd?: string;
  /**
   * 펫 모프
   */
  morphs?: string[];
  /**
   * 펫 형질
   */
  traits?: string[];
  /**
   * 펫 먹이
   */
  foods?: string[];
  /**
   * 판매 상태
   */
  status?: PetControllerGetDeletedPetsStatus;
  /**
   * 펫 성장단계
   */
  growth?: PetControllerGetDeletedPetsGrowthItem[];
  /**
   * 펫 목록 필터링 타입
   */
  filterType?: PetControllerGetDeletedPetsFilterType;
};
