/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type PetControllerGetDeletedPetsSpecies =
  (typeof PetControllerGetDeletedPetsSpecies)[keyof typeof PetControllerGetDeletedPetsSpecies];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetControllerGetDeletedPetsSpecies = {
  CR: "CR",
  LE: "LE",
  FT: "FT",
  KN: "KN",
  LC: "LC",
  GG: "GG",
} as const;
