/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type PetControllerUnlinkParentRole =
  (typeof PetControllerUnlinkParentRole)[keyof typeof PetControllerUnlinkParentRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetControllerUnlinkParentRole = {
  father: "father",
  mother: "mother",
} as const;
