/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type PetControllerGetDeletedPetsFilterType =
  (typeof PetControllerGetDeletedPetsFilterType)[keyof typeof PetControllerGetDeletedPetsFilterType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetControllerGetDeletedPetsFilterType = {
  ALL: "ALL",
  MY: "MY",
  NOT_MY: "NOT_MY",
} as const;
