/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { DeletedPetDto } from "./deletedPetDto";
import type { PageMetaDto } from "./pageMetaDto";

export type PetControllerGetDeletedPets200 = {
  data: DeletedPetDto[];
  meta: PageMetaDto;
};
