/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetParentDto } from "./petParentDto";
import type { PetHiddenStatusDto } from "./petHiddenStatusDto";

/**
 * 엄마 개체 정보
 */
export type PetSummaryAdoptionDtoMother = PetParentDto | PetHiddenStatusDto;
