/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface PriceRangeItemDto {
  /** 분양 수 */
  count: number;
  /** 수익 */
  revenue: number;
  /** 평균 분양가 */
  averagePrice: number;
  /** 가격대 라벨 */
  label: string;
  /** 최소 가격 */
  minPrice: number;
  /** 최대 가격 */
  maxPrice: number;
  /** 비율 (%) */
  percentage: number;
  /** 해당 가격대 분양 ID 목록 */
  adoptionIds: string[];
}
