/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { PetImageItem } from "./petImageItem";

export interface SaveFilesDto {
  /** 펫 이미지 파일 목록 */
  files: PetImageItem[];
}
