/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface SexStatisticsDto {
  /** 수컷 수 */
  male: number;
  /** 암컷 수 */
  female: number;
  /** 미확인 수 */
  unknown: number;
  /** 수컷 비율 (%) */
  maleRate: number;
  /** 암컷 비율 (%) */
  femaleRate: number;
}
