/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { SiblingMatingInfoDtoPairId } from "./siblingMatingInfoDtoPairId";
import type { SiblingMatingInfoDtoMatingDate } from "./siblingMatingInfoDtoMatingDate";

export interface SiblingMatingInfoDto {
  /** 메이팅 ID */
  id: number;
  /** 펫 쌍 ID */
  pairId?: SiblingMatingInfoDtoPairId;
  /** 메이팅 날짜 */
  matingDate?: SiblingMatingInfoDtoMatingDate;
}
