/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { SiblingPetDetailDtoType } from "./siblingPetDetailDtoType";
import type { UserProfilePublicDto } from "./userProfilePublicDto";
import type { SiblingPetDetailDtoSpecies } from "./siblingPetDetailDtoSpecies";
import type { SiblingPetDetailDtoSex } from "./siblingPetDetailDtoSex";
import type { SiblingPetDetailDtoGrowth } from "./siblingPetDetailDtoGrowth";
import type { SiblingLayingInfoDto } from "./siblingLayingInfoDto";
import type { SiblingMatingInfoDto } from "./siblingMatingInfoDto";

export interface SiblingPetDetailDto {
  /** 펫 아이디 */
  petId: string;
  /** 펫 타입(egg/pet) */
  type?: SiblingPetDetailDtoType;
  /** 펫 주인 정보 */
  owner: UserProfilePublicDto;
  /** 펫 이름 */
  name?: string;
  /** 펫 종 */
  species: SiblingPetDetailDtoSpecies;
  /** 펫 출생일 */
  hatchingDate?: string;
  /** 펫 공개 여부 */
  isPublic?: boolean;
  /** 펫 삭제 여부 */
  isDeleted?: boolean;
  /** 펫 성별(수컷, 암컷, 미구분) */
  sex?: SiblingPetDetailDtoSex;
  /** 펫 모프 */
  morphs?: string[];
  /** 펫 형질 */
  traits?: string[];
  /** 펫 성장단계 */
  growth?: SiblingPetDetailDtoGrowth;
  /** 펫 몸무게(g) */
  weight?: number;
  /** 산란 정보 */
  laying?: SiblingLayingInfoDto;
  /** 메이팅 정보 */
  mating?: SiblingMatingInfoDto;
}
