/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface SiblingMatingInfoDto {
  /** 메이팅 ID */
  id: number;
  /** 펫 쌍 ID */
  pairId?: number;
  /** 메이팅 날짜 */
  matingDate?: string;
}
