/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { StatisticsPeriodDtoType } from "./statisticsPeriodDtoType";

export interface StatisticsPeriodDto {
  /** 기간 타입 */
  type: StatisticsPeriodDtoType;
  /** 시즌 (예: 2024-2025) */
  season?: string;
  /** 연도 */
  year?: number;
  /** 월 (1-12) */
  month?: number;
}
