/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 기간 타입
 */
export type StatisticsPeriodDtoType =
  (typeof StatisticsPeriodDtoType)[keyof typeof StatisticsPeriodDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatisticsPeriodDtoType = {
  ALL: "ALL",
  SEASON: "SEASON",
  YEAR_MONTH: "YEAR_MONTH",
} as const;
