/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { StatisticsControllerGetAdoptionStatisticsSpecies } from "./statisticsControllerGetAdoptionStatisticsSpecies";

export type StatisticsControllerGetAdoptionStatisticsParams = {
  /**
   * 연도
   */
  year?: number;
  /**
   * 월 (1-12)
   */
  month?: number;
  /**
   * 종
   */
  species?: StatisticsControllerGetAdoptionStatisticsSpecies;
};
