/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateParentRequestDtoStatus } from "./updateParentRequestDtoStatus";

export interface UpdateParentRequestDto {
  /** 부모 관계 상태 */
  status: UpdateParentRequestDtoStatus;
  /** 거절 사유 */
  rejectReason?: string;
}
