/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

/**
 * 분양 날짜
 */
export type UpdateAdoptionDtoAdoptionDate = { [key: string]: unknown };
