/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateMatingDto {
  /** 아빠 펫 ID */
  fatherId?: string;
  /** 엄마 펫 ID */
  motherId?: string;
  /** 메이팅 날짜 */
  matingDate: string;
  /** 해칭 메모 */
  desc?: string;
}
