/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateParentDtoStatus } from "./updateParentDtoStatus";

export interface UpdateParentDto {
  /** 업데이트 할 부모 관계 상태 */
  status: UpdateParentDtoStatus;
  /** 상대방 유저 ID */
  opponentId: string;
}
