/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { DetailJson } from "./detailJson";
import type { ParentRequestDetailJson } from "./parentRequestDetailJson";

/**
 * 알림 상세 정보 JSON
 */
export type UserNotificationDtoDetailJson = DetailJson | ParentRequestDetailJson;
