/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */

export type UserNotificationControllerGetUnreadCount200 = {
  /** 읽지 않은 알림 개수 */
  count?: number;
};
