/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project Daepa API
 * Project Daepa API description
 * OpenAPI spec version: 1.0
 */
import type { UserNotificationDto } from "./userNotificationDto";

/**
 * 알림 정보
 * @nullable
 */
export type UserNotificationResponseDtoData = UserNotificationDto | null;
